version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: compose_mysql
    restart: always
    volumes:
      - /home/${USER}/data/mysql/data:/var/lib/mysql
      - /home/${USER}/data/mysql/config/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}